spring:
    jpa:
        hibernate:
            ddl-auto: create
    data:
        elasticsearch:
            cluster-name: "#{T(java.util.UUID).randomUUID().toString()}"
            cluster-nodes: localhost:9300
            properties:
                path:
                    logs: target/elasticsearch/log
                    data: target/elasticsearch/data
                    home: src/test/resources/path.home
            repositories:
                enabled: true
logging:
    level:
        org.hibernate.SQL: debug
        com.github.lothar.security.acl: debug